-- Initialize Pokemon Trading Card App Database with Sample Data
USE app_db;

-- Cards from Genetic Apex (A1) set - fetched from TCGdex API
-- Total cards: 286

INSERT INTO Card (cardID, name, packName, rarity, type, imageURL) VALUES
-- 4 Diamond (15 cards),
('A1-004', 'Venusaur ex', 'Mewtwo', '4D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/004/high.webp'),
('A1-023', 'Exeggutor ex', 'Charizard', '4D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/023/high.webp'),
('A1-036', 'Charizard ex', 'Charizard', '4D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/036/high.webp'),
('A1-041', 'Arcanine ex', 'Pikachu', '4D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/041/high.webp'),
('A1-047', 'Moltres ex', 'Charizard', '4D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/047/high.webp'),
('A1-056', 'Blastoise ex', 'Pikachu', '4D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/056/high.webp'),
('A1-076', 'Starmie ex', 'Charizard', '4D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/076/high.webp'),
('A1-084', 'Articuno ex', 'Mewtwo', '4D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/084/high.webp'),
('A1-096', 'Pikachu ex', 'Pikachu', '4D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/096/high.webp'),
('A1-104', 'Zapdos ex', 'Pikachu', '4D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/104/high.webp'),
('A1-123', 'Gengar ex', 'Mewtwo', '4D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/123/high.webp'),
('A1-129', 'Mewtwo ex', 'Mewtwo', '4D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/129/high.webp'),
('A1-146', 'Machamp ex', 'Charizard', '4D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/146/high.webp'),
('A1-153', 'Marowak ex', 'Mewtwo', '4D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/153/high.webp'),
('A1-195', 'Wigglytuff ex', 'Pikachu', '4D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/195/high.webp'),
-- 3 Diamond (42 cards),
('A1-003', 'Venusaur', 'Mewtwo', '3D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/003/high.webp'),
('A1-007', 'Butterfree', 'Pikachu', '3D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/007/high.webp'),
('A1-010', 'Beedrill', 'Mewtwo', '3D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/010/high.webp'),
('A1-013', 'Vileplume', 'Charizard', '3D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/013/high.webp'),
('A1-020', 'Victreebel', 'Charizard', '3D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/020/high.webp'),
('A1-022', 'Exeggutor', 'Charizard', '3D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/022/high.webp'),
('A1-035', 'Charizard', 'Charizard', '3D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/035/high.webp'),
('A1-040', 'Arcanine', 'Pikachu', '3D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/040/high.webp'),
('A1-045', 'Flareon', 'Charizard', '3D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/045/high.webp'),
('A1-046', 'Moltres', 'Charizard', '3D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/046/high.webp'),
('A1-055', 'Blastoise', 'Pikachu', '3D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/055/high.webp'),
('A1-061', 'Poliwrath', 'Charizard', '3D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/061/high.webp'),
('A1-078', 'Gyarados', 'Pikachu', '3D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/078/high.webp'),
('A1-079', 'Lapras', 'Charizard', '3D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/079/high.webp'),
('A1-080', 'Vaporeon', 'Mewtwo', '3D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/080/high.webp'),
('A1-082', 'Omastar', 'Pikachu', '3D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/082/high.webp'),
('A1-083', 'Articuno', 'Mewtwo', '3D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/083/high.webp'),
('A1-089', 'Greninja', 'Charizard', '3D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/089/high.webp'),
('A1-095', 'Raichu', 'Pikachu', '3D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/095/high.webp'),
('A1-098', 'Magneton', 'Pikachu', '3D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/098/high.webp'),
('A1-102', 'Jolteon', 'Pikachu', '3D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/102/high.webp'),
('A1-103', 'Zapdos', 'Pikachu', '3D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/103/high.webp'),
('A1-109', 'Eelektross', 'Mewtwo', '3D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/109/high.webp'),
('A1-117', 'Alakazam', 'Charizard', '3D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/117/high.webp'),
('A1-122', 'Gengar', 'Mewtwo', '3D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/122/high.webp'),
('A1-125', 'Hypno', 'Pikachu', '3D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/125/high.webp'),
('A1-128', 'Mewtwo', 'Mewtwo', '3D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/128/high.webp'),
('A1-132', 'Gardevoir', 'Mewtwo', '3D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/132/high.webp'),
('A1-145', 'Machamp', 'Charizard', '3D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/145/high.webp'),
('A1-149', 'Golem', 'Pikachu', '3D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/149/high.webp'),
('A1-159', 'Kabutops', 'Charizard', '3D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/159/high.webp'),
('A1-168', 'Nidoqueen', 'Pikachu', '3D', 'Darkness', 'https://assets.tcgdex.net/en/tcgp/A1/168/high.webp'),
('A1-171', 'Nidoking', 'Pikachu', '3D', 'Darkness', 'https://assets.tcgdex.net/en/tcgp/A1/171/high.webp'),
('A1-175', 'Muk', 'Mewtwo', '3D', 'Darkness', 'https://assets.tcgdex.net/en/tcgp/A1/175/high.webp'),
('A1-177', 'Weezing', 'Mewtwo', '3D', 'Darkness', 'https://assets.tcgdex.net/en/tcgp/A1/177/high.webp'),
('A1-182', 'Melmetal', 'Charizard', '3D', 'Metal', 'https://assets.tcgdex.net/en/tcgp/A1/182/high.webp'),
('A1-185', 'Dragonite', 'Mewtwo', '3D', 'Dragon', 'https://assets.tcgdex.net/en/tcgp/A1/185/high.webp'),
('A1-188', 'Pidgeot', 'Mewtwo', '3D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/188/high.webp'),
('A1-203', 'Kangaskhan', 'Charizard', '3D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/203/high.webp'),
('A1-205', 'Ditto', 'Mewtwo', '3D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/205/high.webp'),
('A1-210', 'Aerodactyl', 'Mewtwo', '3D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/210/high.webp'),
('A1-211', 'Snorlax', 'Pikachu', '3D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/211/high.webp'),
-- 2 Diamond (69 cards),
('A1-002', 'Ivysaur', 'Mewtwo', '2D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/002/high.webp'),
('A1-012', 'Gloom', 'Charizard', '2D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/012/high.webp'),
('A1-015', 'Parasect', 'Pikachu', '2D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/015/high.webp'),
('A1-017', 'Venomoth', 'Mewtwo', '2D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/017/high.webp'),
('A1-019', 'Weepinbell', 'Charizard', '2D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/019/high.webp'),
('A1-026', 'Pinsir', 'Mewtwo', '2D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/026/high.webp'),
('A1-028', 'Whimsicott', 'Mewtwo', '2D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/028/high.webp'),
('A1-030', 'Lilligant', 'Mewtwo', '2D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/030/high.webp'),
('A1-034', 'Charmeleon', 'Charizard', '2D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/034/high.webp'),
('A1-038', 'Ninetales', 'Charizard', '2D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/038/high.webp'),
('A1-043', 'Rapidash', 'Mewtwo', '2D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/043/high.webp'),
('A1-052', 'Centiskorch', 'Mewtwo', '2D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/052/high.webp'),
('A1-054', 'Wartortle', 'Pikachu', '2D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/054/high.webp'),
('A1-058', 'Golduck', 'Mewtwo', '2D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/058/high.webp'),
('A1-060', 'Poliwhirl', 'Charizard', '2D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/060/high.webp'),
('A1-063', 'Tentacruel', 'Mewtwo', '2D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/063/high.webp'),
('A1-065', 'Dewgong', 'Pikachu', '2D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/065/high.webp'),
('A1-067', 'Cloyster', 'Mewtwo', '2D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/067/high.webp'),
('A1-069', 'Kingler', 'Mewtwo', '2D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/069/high.webp'),
('A1-071', 'Seadra', 'Pikachu', '2D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/071/high.webp'),
('A1-075', 'Starmie', 'Charizard', '2D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/075/high.webp'),
('A1-081', 'Omanyte', 'Pikachu', '2D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/081/high.webp'),
('A1-086', 'Swanna', 'Charizard', '2D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/086/high.webp'),
('A1-088', 'Frogadier', 'Charizard', '2D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/088/high.webp'),
('A1-091', 'Bruxish', 'Mewtwo', '2D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/091/high.webp'),
('A1-093', 'Frosmoth', 'Mewtwo', '2D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/093/high.webp'),
('A1-100', 'Electrode', 'Pikachu', '2D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/100/high.webp'),
('A1-106', 'Zebstrika', 'Mewtwo', '2D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/106/high.webp'),
('A1-108', 'Eelektrik', 'Mewtwo', '2D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/108/high.webp'),
('A1-112', 'Pincurchin', 'Mewtwo', '2D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/112/high.webp'),
('A1-114', 'Clefable', 'Pikachu', '2D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/114/high.webp'),
('A1-116', 'Kadabra', 'Charizard', '2D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/116/high.webp'),
('A1-119', 'Slowbro', 'Mewtwo', '2D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/119/high.webp'),
('A1-121', 'Haunter', 'Mewtwo', '2D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/121/high.webp'),
('A1-126', 'Mr. Mime', 'Mewtwo', '2D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/126/high.webp'),
('A1-131', 'Kirlia', 'Mewtwo', '2D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/131/high.webp'),
('A1-136', 'Golurk', 'Mewtwo', '2D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/136/high.webp'),
('A1-138', 'Sandslash', 'Mewtwo', '2D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/138/high.webp'),
('A1-140', 'Dugtrio', 'Pikachu', '2D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/140/high.webp'),
('A1-142', 'Primeape', 'Charizard', '2D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/142/high.webp'),
('A1-144', 'Machoke', 'Charizard', '2D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/144/high.webp'),
('A1-148', 'Graveler', 'Pikachu', '2D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/148/high.webp'),
('A1-150', 'Onix', 'Pikachu', '2D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/150/high.webp'),
('A1-152', 'Marowak', 'Mewtwo', '2D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/152/high.webp'),
('A1-157', 'Rhydon', 'Mewtwo', '2D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/157/high.webp'),
('A1-158', 'Kabuto', 'Charizard', '2D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/158/high.webp'),
('A1-161', 'Mienshao', 'Pikachu', '2D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/161/high.webp'),
('A1-163', 'Grapploct', 'Mewtwo', '2D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/163/high.webp'),
('A1-165', 'Arbok', 'Mewtwo', '2D', 'Darkness', 'https://assets.tcgdex.net/en/tcgp/A1/165/high.webp'),
('A1-167', 'Nidorina', 'Pikachu', '2D', 'Darkness', 'https://assets.tcgdex.net/en/tcgp/A1/167/high.webp'),
('A1-170', 'Nidorino', 'Pikachu', '2D', 'Darkness', 'https://assets.tcgdex.net/en/tcgp/A1/170/high.webp'),
('A1-173', 'Golbat', 'Mewtwo', '2D', 'Darkness', 'https://assets.tcgdex.net/en/tcgp/A1/173/high.webp'),
('A1-180', 'Bisharp', 'Mewtwo', '2D', 'Metal', 'https://assets.tcgdex.net/en/tcgp/A1/180/high.webp'),
('A1-184', 'Dragonair', 'Mewtwo', '2D', 'Dragon', 'https://assets.tcgdex.net/en/tcgp/A1/184/high.webp'),
('A1-197', 'Persian', 'Charizard', '2D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/197/high.webp'),
('A1-200', 'Dodrio', 'Mewtwo', '2D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/200/high.webp'),
('A1-201', 'Lickitung', 'Mewtwo', '2D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/201/high.webp'),
('A1-202', 'Chansey', 'Pikachu', '2D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/202/high.webp'),
('A1-204', 'Tauros', 'Charizard', '2D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/204/high.webp'),
('A1-209', 'Porygon', 'Mewtwo', '2D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/209/high.webp'),
('A1-213', 'Cinccino', 'Mewtwo', '2D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/213/high.webp'),
('A1-219', 'Erika', 'Charizard', '2D', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/219/high.webp'),
('A1-220', 'Misty', 'Pikachu', '2D', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/220/high.webp'),
('A1-221', 'Blaine', 'Charizard', '2D', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/221/high.webp'),
('A1-222', 'Koga', 'Mewtwo', '2D', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/222/high.webp'),
('A1-223', 'Giovanni', 'Mewtwo', '2D', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/223/high.webp'),
('A1-224', 'Brock', 'Pikachu', '2D', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/224/high.webp'),
('A1-225', 'Sabrina', 'Charizard', '2D', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/225/high.webp'),
('A1-226', 'Lt. Surge', 'Pikachu', '2D', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/226/high.webp'),
-- 1 Diamond (102 cards),
('A1-001', 'Bulbasaur', 'Mewtwo', '1D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/001/high.webp'),
('A1-005', 'Caterpie', 'Pikachu', '1D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/005/high.webp'),
('A1-006', 'Metapod', 'Pikachu', '1D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/006/high.webp'),
('A1-008', 'Weedle', 'Mewtwo', '1D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/008/high.webp'),
('A1-009', 'Kakuna', 'Mewtwo', '1D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/009/high.webp'),
('A1-011', 'Oddish', 'Charizard', '1D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/011/high.webp'),
('A1-014', 'Paras', 'Pikachu', '1D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/014/high.webp'),
('A1-016', 'Venonat', 'Mewtwo', '1D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/016/high.webp'),
('A1-018', 'Bellsprout', 'Charizard', '1D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/018/high.webp'),
('A1-021', 'Exeggcute', 'Charizard', '1D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/021/high.webp'),
('A1-024', 'Tangela', 'Charizard', '1D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/024/high.webp'),
('A1-025', 'Scyther', 'Mewtwo', '1D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/025/high.webp'),
('A1-027', 'Cottonee', 'Mewtwo', '1D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/027/high.webp'),
('A1-029', 'Petilil', 'Mewtwo', '1D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/029/high.webp'),
('A1-031', 'Skiddo', 'Charizard', '1D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/031/high.webp'),
('A1-032', 'Gogoat', 'Charizard', '1D', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/032/high.webp'),
('A1-033', 'Charmander', 'Charizard', '1D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/033/high.webp'),
('A1-037', 'Vulpix', 'Charizard', '1D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/037/high.webp'),
('A1-039', 'Growlithe', 'Pikachu', '1D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/039/high.webp'),
('A1-042', 'Ponyta', 'Mewtwo', '1D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/042/high.webp'),
('A1-044', 'Magmar', 'Charizard', '1D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/044/high.webp'),
('A1-048', 'Heatmor', 'Mewtwo', '1D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/048/high.webp'),
('A1-049', 'Salandit', 'Mewtwo', '1D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/049/high.webp'),
('A1-050', 'Salazzle', 'Mewtwo', '1D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/050/high.webp'),
('A1-051', 'Sizzlipede', 'Mewtwo', '1D', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/051/high.webp'),
('A1-053', 'Squirtle', 'Pikachu', '1D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/053/high.webp'),
('A1-057', 'Psyduck', 'Mewtwo', '1D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/057/high.webp'),
('A1-059', 'Poliwag', 'Charizard', '1D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/059/high.webp'),
('A1-062', 'Tentacool', 'Mewtwo', '1D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/062/high.webp'),
('A1-064', 'Seel', 'Pikachu', '1D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/064/high.webp'),
('A1-066', 'Shellder', 'Mewtwo', '1D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/066/high.webp'),
('A1-068', 'Krabby', 'Mewtwo', '1D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/068/high.webp'),
('A1-070', 'Horsea', 'Pikachu', '1D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/070/high.webp'),
('A1-072', 'Goldeen', 'Pikachu', '1D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/072/high.webp'),
('A1-073', 'Seaking', 'Pikachu', '1D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/073/high.webp'),
('A1-074', 'Staryu', 'Charizard', '1D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/074/high.webp'),
('A1-077', 'Magikarp', 'Pikachu', '1D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/077/high.webp'),
('A1-085', 'Ducklett', 'Charizard', '1D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/085/high.webp'),
('A1-087', 'Froakie', 'Charizard', '1D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/087/high.webp'),
('A1-090', 'Pyukumuku', 'Charizard', '1D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/090/high.webp'),
('A1-092', 'Snom', 'Mewtwo', '1D', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/092/high.webp'),
('A1-094', 'Pikachu', 'Pikachu', '1D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/094/high.webp'),
('A1-097', 'Magnemite', 'Pikachu', '1D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/097/high.webp'),
('A1-099', 'Voltorb', 'Pikachu', '1D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/099/high.webp'),
('A1-101', 'Electabuzz', 'Pikachu', '1D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/101/high.webp'),
('A1-105', 'Blitzle', 'Mewtwo', '1D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/105/high.webp'),
('A1-107', 'Tynamo', 'Mewtwo', '1D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/107/high.webp'),
('A1-110', 'Helioptile', 'Mewtwo', '1D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/110/high.webp'),
('A1-111', 'Heliolisk', 'Mewtwo', '1D', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/111/high.webp'),
('A1-113', 'Clefairy', 'Pikachu', '1D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/113/high.webp'),
('A1-115', 'Abra', 'Charizard', '1D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/115/high.webp'),
('A1-118', 'Slowpoke', 'Mewtwo', '1D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/118/high.webp'),
('A1-120', 'Gastly', 'Mewtwo', '1D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/120/high.webp'),
('A1-124', 'Drowzee', 'Pikachu', '1D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/124/high.webp'),
('A1-127', 'Jynx', 'Mewtwo', '1D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/127/high.webp'),
('A1-130', 'Ralts', 'Mewtwo', '1D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/130/high.webp'),
('A1-133', 'Woobat', 'Mewtwo', '1D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/133/high.webp'),
('A1-134', 'Swoobat', 'Mewtwo', '1D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/134/high.webp'),
('A1-135', 'Golett', 'Mewtwo', '1D', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/135/high.webp'),
('A1-137', 'Sandshrew', 'Mewtwo', '1D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/137/high.webp'),
('A1-139', 'Diglett', 'Pikachu', '1D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/139/high.webp'),
('A1-141', 'Mankey', 'Charizard', '1D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/141/high.webp'),
('A1-143', 'Machop', 'Charizard', '1D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/143/high.webp'),
('A1-147', 'Geodude', 'Pikachu', '1D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/147/high.webp'),
('A1-151', 'Cubone', 'Mewtwo', '1D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/151/high.webp'),
('A1-154', 'Hitmonlee', 'Mewtwo', '1D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/154/high.webp'),
('A1-155', 'Hitmonchan', 'Charizard', '1D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/155/high.webp'),
('A1-156', 'Rhyhorn', 'Mewtwo', '1D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/156/high.webp'),
('A1-160', 'Mienfoo', 'Pikachu', '1D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/160/high.webp'),
('A1-162', 'Clobbopus', 'Mewtwo', '1D', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/162/high.webp'),
('A1-164', 'Ekans', 'Mewtwo', '1D', 'Darkness', 'https://assets.tcgdex.net/en/tcgp/A1/164/high.webp'),
('A1-166', 'Nidoran♀', 'Pikachu', '1D', 'Darkness', 'https://assets.tcgdex.net/en/tcgp/A1/166/high.webp'),
('A1-169', 'Nidoran♂', 'Pikachu', '1D', 'Darkness', 'https://assets.tcgdex.net/en/tcgp/A1/169/high.webp'),
('A1-172', 'Zubat', 'Mewtwo', '1D', 'Darkness', 'https://assets.tcgdex.net/en/tcgp/A1/172/high.webp'),
('A1-174', 'Grimer', 'Mewtwo', '1D', 'Darkness', 'https://assets.tcgdex.net/en/tcgp/A1/174/high.webp'),
('A1-176', 'Koffing', 'Mewtwo', '1D', 'Darkness', 'https://assets.tcgdex.net/en/tcgp/A1/176/high.webp'),
('A1-178', 'Mawile', 'Charizard', '1D', 'Metal', 'https://assets.tcgdex.net/en/tcgp/A1/178/high.webp'),
('A1-179', 'Pawniard', 'Mewtwo', '1D', 'Metal', 'https://assets.tcgdex.net/en/tcgp/A1/179/high.webp'),
('A1-181', 'Meltan', 'Charizard', '1D', 'Metal', 'https://assets.tcgdex.net/en/tcgp/A1/181/high.webp'),
('A1-183', 'Dratini', 'Mewtwo', '1D', 'Dragon', 'https://assets.tcgdex.net/en/tcgp/A1/183/high.webp'),
('A1-186', 'Pidgey', 'Mewtwo', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/186/high.webp'),
('A1-187', 'Pidgeotto', 'Mewtwo', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/187/high.webp'),
('A1-189', 'Rattata', 'Mewtwo', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/189/high.webp'),
('A1-190', 'Raticate', 'Mewtwo', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/190/high.webp'),
('A1-191', 'Spearow', 'Charizard', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/191/high.webp'),
('A1-192', 'Fearow', 'Charizard', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/192/high.webp'),
('A1-193', 'Jigglypuff', 'Pikachu', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/193/high.webp'),
('A1-194', 'Wigglytuff', 'Pikachu', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/194/high.webp'),
('A1-196', 'Meowth', 'Charizard', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/196/high.webp'),
('A1-198', 'Farfetch''d', 'Mewtwo', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/198/high.webp'),
('A1-199', 'Doduo', 'Mewtwo', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/199/high.webp'),
('A1-206', 'Eevee', 'Charizard', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/206/high.webp'),
('A1-207', 'Eevee', 'Mewtwo', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/207/high.webp'),
('A1-208', 'Eevee', 'Pikachu', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/208/high.webp'),
('A1-212', 'Minccino', 'Mewtwo', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/212/high.webp'),
('A1-214', 'Wooloo', 'Mewtwo', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/214/high.webp'),
('A1-215', 'Dubwool', 'Mewtwo', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/215/high.webp'),
('A1-216', 'Helix Fossil', 'Pikachu', '1D', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/216/high.webp'),
('A1-217', 'Dome Fossil', 'Charizard', '1D', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/217/high.webp'),
('A1-218', 'Old Amber', 'Mewtwo', '1D', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/218/high.webp'),
('A1-265', 'Wigglytuff ex', 'Pikachu', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/265/high.webp'),
('A1-279', 'Wigglytuff ex', 'Pikachu', '1D', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/279/high.webp'),
-- 3 Star (4 cards),
('A1-280', 'Charizard ex', 'Charizard', '3S', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/280/high.webp'),
('A1-281', 'Pikachu ex', 'Pikachu', '3S', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/281/high.webp'),
('A1-282', 'Mewtwo ex', 'Mewtwo', '3S', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/282/high.webp'),
('A1-283', 'Mew', 'Shared', '3S', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/283/high.webp'),
-- 2 Star (27 cards),
('A1-251', 'Venusaur ex', 'Mewtwo', '2S', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/251/high.webp'),
('A1-252', 'Exeggutor ex', 'Charizard', '2S', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/252/high.webp'),
('A1-253', 'Charizard ex', 'Charizard', '2S', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/253/high.webp'),
('A1-254', 'Arcanine ex', 'Pikachu', '2S', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/254/high.webp'),
('A1-255', 'Moltres ex', 'Charizard', '2S', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/255/high.webp'),
('A1-256', 'Blastoise ex', 'Pikachu', '2S', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/256/high.webp'),
('A1-257', 'Starmie ex', 'Charizard', '2S', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/257/high.webp'),
('A1-258', 'Articuno ex', 'Mewtwo', '2S', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/258/high.webp'),
('A1-259', 'Pikachu ex', 'Pikachu', '2S', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/259/high.webp'),
('A1-260', 'Zapdos ex', 'Pikachu', '2S', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/260/high.webp'),
('A1-261', 'Gengar ex', 'Mewtwo', '2S', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/261/high.webp'),
('A1-262', 'Mewtwo ex', 'Mewtwo', '2S', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/262/high.webp'),
('A1-263', 'Machamp ex', 'Charizard', '2S', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/263/high.webp'),
('A1-264', 'Marowak ex', 'Mewtwo', '2S', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/264/high.webp'),
('A1-266', 'Erika', 'Charizard', '2S', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/266/high.webp'),
('A1-267', 'Misty', 'Pikachu', '2S', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/267/high.webp'),
('A1-268', 'Blaine', 'Charizard', '2S', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/268/high.webp'),
('A1-269', 'Koga', 'Mewtwo', '2S', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/269/high.webp'),
('A1-270', 'Giovanni', 'Mewtwo', '2S', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/270/high.webp'),
('A1-271', 'Brock', 'Pikachu', '2S', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/271/high.webp'),
('A1-272', 'Sabrina', 'Charizard', '2S', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/272/high.webp'),
('A1-273', 'Lt. Surge', 'Pikachu', '2S', 'Trainer', 'https://assets.tcgdex.net/en/tcgp/A1/273/high.webp'),
('A1-274', 'Moltres ex', 'Charizard', '2S', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/274/high.webp'),
('A1-275', 'Articuno ex', 'Mewtwo', '2S', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/275/high.webp'),
('A1-276', 'Zapdos ex', 'Pikachu', '2S', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/276/high.webp'),
('A1-277', 'Gengar ex', 'Mewtwo', '2S', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/277/high.webp'),
('A1-278', 'Machamp ex', 'Charizard', '2S', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/278/high.webp'),
-- 1 Star (24 cards),
('A1-227', 'Bulbasaur', 'Mewtwo', '1S', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/227/high.webp'),
('A1-228', 'Gloom', 'Charizard', '1S', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/228/high.webp'),
('A1-229', 'Pinsir', 'Charizard', '1S', 'Grass', 'https://assets.tcgdex.net/en/tcgp/A1/229/high.webp'),
('A1-230', 'Charmander', 'Charizard', '1S', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/230/high.webp'),
('A1-231', 'Rapidash', 'Charizard', '1S', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/231/high.webp'),
('A1-232', 'Squirtle', 'Pikachu', '1S', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/232/high.webp'),
('A1-233', 'Gyarados', 'Pikachu', '1S', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/233/high.webp'),
('A1-234', 'Lapras', 'Charizard', '1S', 'Water', 'https://assets.tcgdex.net/en/tcgp/A1/234/high.webp'),
('A1-235', 'Electrode', 'Pikachu', '1S', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/235/high.webp'),
('A1-236', 'Alakazam', 'Charizard', '1S', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/236/high.webp'),
('A1-237', 'Slowpoke', 'Charizard', '1S', 'Psychic', 'https://assets.tcgdex.net/en/tcgp/A1/237/high.webp'),
('A1-238', 'Diglett', 'Pikachu', '1S', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/238/high.webp'),
('A1-239', 'Cubone', 'Mewtwo', '1S', 'Fighting', 'https://assets.tcgdex.net/en/tcgp/A1/239/high.webp'),
('A1-240', 'Nidoqueen', 'Pikachu', '1S', 'Darkness', 'https://assets.tcgdex.net/en/tcgp/A1/240/high.webp'),
('A1-241', 'Nidoking', 'Pikachu', '1S', 'Darkness', 'https://assets.tcgdex.net/en/tcgp/A1/241/high.webp'),
('A1-242', 'Golbat', 'Mewtwo', '1S', 'Darkness', 'https://assets.tcgdex.net/en/tcgp/A1/242/high.webp'),
('A1-243', 'Weezing', 'Mewtwo', '1S', 'Darkness', 'https://assets.tcgdex.net/en/tcgp/A1/243/high.webp'),
('A1-244', 'Dragonite', 'Mewtwo', '1S', 'Dragon', 'https://assets.tcgdex.net/en/tcgp/A1/244/high.webp'),
('A1-245', 'Pidgeot', 'Mewtwo', '1S', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/245/high.webp'),
('A1-246', 'Meowth', 'Charizard', '1S', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/246/high.webp'),
('A1-247', 'Ditto', 'Mewtwo', '1S', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/247/high.webp'),
('A1-248', 'Eevee', 'Pikachu', '1S', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/248/high.webp'),
('A1-249', 'Porygon', 'Mewtwo', '1S', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/249/high.webp'),
('A1-250', 'Snorlax', 'Pikachu', '1S', 'Colorless', 'https://assets.tcgdex.net/en/tcgp/A1/250/high.webp'),
-- Crown (3 cards),
('A1-284', 'Charizard ex', 'Mewtwo', 'C', 'Fire', 'https://assets.tcgdex.net/en/tcgp/A1/284/high.webp'),
('A1-285', 'Pikachu ex', 'Mewtwo', 'C', 'Lightning', 'https://assets.tcgdex.net/en/tcgp/A1/285/high.webp');